In [27]:
import pandas as pd 
import sqlite3

In [28]:
conn = sqlite3.connect('ecommerce-sales.db')

In [29]:
pd.read_sql("SELECT name FROM sqlite_master WHERE TYPE = 'table'",conn)

            name
0     categories
1      customers
2         orders
3    order_items
4       payments
5       products
6     sales_info
7  customer_info
8  products_info
9      sale_info

## **--------------Getting sales_info Tables Datas--------------------**

In [30]:
complete_sales_info = pd.read_sql("SELECT * FROM sale_info",conn)
complete_sales_info

,customer_id,order_id,product_id,order_date,order_status,order_channel,shipping_state,shipping_city,shipping_fee,order_total,order_subtotal,quantity,unit_price,discount_percent,line_total,payment_method,payment_status,amount,transaction_fee
0,100438,700000,5276,2025-11-09 16:03:23,Delivered,Website,Delhi,Delhi,0.0,5729.43,5729.43,2,463.18,0,926.36,Debit Card,Completed,5729.43,103.13
1,100438,700000,5312,2025-11-09 16:03:23,Delivered,Website,Delhi,Delhi,0.0,5729.43,5729.43,2,2527.93,5,4803.07,Debit Card,Completed,5729.43,103.13
2,100568,700001,5259,2024-01-26 17:25:29,Delivered,Website,Tamil Nadu,Chennai,0.0,11589.47,11589.47,3,2094.33,0,6282.99,Credit Card,Completed,11589.47,208.61
3,100568,700001,5312,2024-01-26 17:25:29,Delivered,Website,Tamil Nadu,Chennai,0.0,11589.47,11589.47,1,2527.93,10,2275.14,Credit Card,Completed,11589.47,208.61
4,100568,700001,5483,2024-01-26 17:25:29,Delivered,Website,Tamil Nadu,Chennai,0.0,11589.47,11589.47,4,797.72,5,3031.34,Credit Card,Completed,11589.47,208.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28531,102907,711998,5483,2023-12-22 16:59:35,Delivered,Website,Tamil Nadu,Chennai,0.0,222069.02,222069.02,3,797.72,10,2153.84,Debit Card,Completed,222069.02,3997.24
28532,101018,711999,5042,2025-08-22 22:37:10,Delivered,Mobile App,Gujarat,Ahmedabad,0.0,81334.36,81334.36,1,66334.75,0,66334.75,Debit Card,Completed,81334.36,1464.02
28533,101018,711999,5276,2025-08-22 22:37:10,Delivered,Mobile App,Gujarat,Ahmedabad,0.0,81334.36,81334.36,4,463.18,0,1852.72,Debit Card,Completed,81334.36,1464.02
28534,101018,711999,5312,2025-08-22 22:37:10,Delivered,Mobile App,Gujarat,Ahmedabad,0.0,81334.36,81334.36,5,2527.93,0,12639.65,Debit Card,Completed,81334.36,1464.02
28535,101018,711999,5479,2025-08-22 22:37:10,Delivered,Mobile App,Gujarat,Ahmedabad,0.0,81334.36,81334.36,1,507.24,0,507.24,Debit Card,Completed,81334.36,1464.02

## **--------------Storing sales_info Tables Datas In  sql-server--------------------**

In [31]:
import urllib
import logging
from sqlalchemy import create_engine


# ---------------------------------------------------------
# Logging Configuration
# ---------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    filename = 'D:\project_pandas\project_01\log\load_cleaned_data_in_sql-server.logs',
    format="%(asctime)s | %(levelname)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    force = True
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------
# SQL Server Configuration
# ---------------------------------------------------------

SERVER = r"MADARA7998\SQLEXPRESS"
DATABASE = "ecommerce_db"
TABLE_NAME = "sales_info"
SCHEMA = "godl"


# ---------------------------------------------------------
# Create SQL Server Connection
# ---------------------------------------------------------

logger.info("Creating SQL Server connection...")

connection_string = (
    "DRIVER={ODBC Driver 17 for SQL Server};"
    f"SERVER={SERVER};"
    f"DATABASE={DATABASE};"
    "Trusted_Connection=yes;"
)

params = urllib.parse.quote_plus(connection_string)

engine = create_engine(
    f"mssql+pyodbc:///?odbc_connect={params}"
)

logger.info("SQLAlchemy engine created successfully.")


# ---------------------------------------------------------
# Upload DataFrame to SQL Server
# ---------------------------------------------------------

try:
    logger.info(
        "Starting data upload: %s.%s",
        SCHEMA,
        TABLE_NAME
    )

    logger.info(
        "Rows to upload: %s",
        len(complete_sales_info)
    )

    complete_sales_info.to_sql(
        name=TABLE_NAME,
        schema=SCHEMA,
        con=engine,
        if_exists="replace",
        index=False,
        chunksize=500
    )

    logger.info(
        "Data uploaded successfully to [%s].[%s]",
        SCHEMA,
        TABLE_NAME
    )
    print(f"Data uploaded successfully to scheme : {SCHEMA}  & table : {TABLE_NAME}" )

except Exception as e:
    logger.exception(
        "Error uploading data to SQL Server: %s",
        e
    )
    print("Error uploading data to SQL Server: %s",e)

Data uploaded successfully to scheme : godl  & table : sales_info

## **--------------Getting products_info Tables Datas--------------------**

In [22]:
product_info = pd.read_sql("SELECT * FROM products_info",conn)
product_info

,category_id,category_name,department,product_id,product_name,product_brand,cost_price,unit_price,stock_quantity,is_active,created_date,avg_rating
0,1001,Mobiles & Accessories,Electronics,5000,boAt Premium Smartphone,boAt,23874.66,38584.86,100,1,2024-11-11,4.0
1,1001,Mobiles & Accessories,Electronics,5001,boAt Pro Earbuds,boAt,15411.68,26773.87,5,1,2023-01-27,4.0
2,1001,Mobiles & Accessories,Electronics,5002,Apple Classic Power Bank,Apple,43454.86,66294.67,0,0,2023-10-20,4.6
3,1001,Mobiles & Accessories,Electronics,5003,Xiaomi Classic Smartphone,Xiaomi,14475.49,23801.91,20,1,2023-08-26,4.4
4,1001,Mobiles & Accessories,Electronics,5004,Apple Premium Power Bank,Apple,20372.26,33970.22,50,1,2025-02-23,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
595,1038,Bike Accessories,Automotive,5595,GlowUp Premium Helmet,GlowUp,2468.16,4083.15,100,1,2025-07-26,3.6
596,1038,Bike Accessories,Automotive,5596,PureGlow Premium Bike Cover,PureGlow,1187.21,1866.30,100,1,2025-01-16,5.0
597,1038,Bike Accessories,Automotive,5597,Urbanic Smart Bike Cover,Urbanic,2249.16,2870.12,50,1,2023-10-22,4.5
598,1038,Bike Accessories,Automotive,5598,Urbanic Comfort Bike Cover,Urbanic,2146.73,3452.59,20,1,2023-01-11,3.5
599,1038,Bike Accessories,Automotive,5599,ChefMate Pro Bike Cover,ChefMate,2143.44,3017.31,50,1,2025-10-06,3.5

## **--------------Storing products_info Tables Datas In  sql-server--------------------**

In [24]:
import urllib
import logging
from sqlalchemy import create_engine


# ---------------------------------------------------------
# Logging Configuration
# ---------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    filename = 'D:\project_pandas\project_01\log\load_cleaned_data_in_sql-server.logs',
    format="%(asctime)s | %(levelname)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    force = True
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------
# SQL Server Configuration
# ---------------------------------------------------------

SERVER = r"MADARA7998\SQLEXPRESS"
DATABASE = "ecommerce_db"
TABLE_NAME = "product_info"
SCHEMA = "godl"


# ---------------------------------------------------------
# Create SQL Server Connection
# ---------------------------------------------------------

logger.info("Creating SQL Server connection...")

connection_string = (
    "DRIVER={ODBC Driver 17 for SQL Server};"
    f"SERVER={SERVER};"
    f"DATABASE={DATABASE};"
    "Trusted_Connection=yes;"
)

params = urllib.parse.quote_plus(connection_string)

engine = create_engine(
    f"mssql+pyodbc:///?odbc_connect={params}"
)

logger.info("SQLAlchemy engine created successfully.")


# ---------------------------------------------------------
# Upload DataFrame to SQL Server
# ---------------------------------------------------------

try:
    logger.info(
        "Starting data upload: %s.%s",
        SCHEMA,
        TABLE_NAME
    )

    logger.info(
        "Rows to upload: %s",
        len(product_info)
    )

    product_info.to_sql(
        name=TABLE_NAME,
        schema=SCHEMA,
        con=engine,
        if_exists="replace",
        index=False,
        chunksize=500
    )

    logger.info(
        "Data uploaded successfully to [%s].[%s]",
        SCHEMA,
        TABLE_NAME
    )
    print(f"Data uploaded successfully to scheme : {SCHEMA}  & table : {TABLE_NAME}" )

except Exception as e:
    logger.exception(
        "Error uploading data to SQL Server: %s",
        e
    )
    print("Error uploading data to SQL Server: %s",e)

Data uploaded successfully to scheme : godl  & table : product_info

## **--------------Getting customer_info Tables Datas--------------------**

In [25]:
customer_data = pd.read_sql("SELECT * FROM customer_info",conn)
customer_data

,customer_id,customer_name,email,phone,gender,date_of_birth,city,state,country,signup_date,cuatomer_segment,is_subscribed_newsletter
0,100000,Chaman Khurana,chaman.khurana913@outlook.com,07701436349,Female,1978-04-29,Indore,Madhya Pradesh,India,2024-09-19,HIGH,1
1,100001,Orinder Sandal,orinder.sandal670@yahoo.com,04431351823,Male,1970-12-31,Chandigarh,Chandigarh,India,2023-12-29,HIGH,0
2,100003,Edhitha Swaminathan,edhitha.swaminathan472@yahoo.com,07752047116,Female,1984-03-20,Pune,Maharashtra,India,2023-02-07,MEDIUN,0
3,100004,Avni Doshi,avni.doshi247@gmail.com,8699938677,Female,1974-11-20,Indore,Madhya Pradesh,India,2024-02-24,LOW,1
4,100006,Vrinda Manne,vrinda.manne240@outlook.com,3493618324,Female,2000-04-16,Ahmedabad,Gujarat,India,2025-01-11,MEDIUN,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2001,102993,Chaitaly Sathe,chaitaly.sathe963@outlook.com,08796338790,Female,2001-01-05,Lucknow,Uttar Pradesh,India,2024-01-05,LOW,0
2002,102994,Bhavya Handa,bhavya.handa363@hotmail.com,2204484351,Female,1989-08-04,Chandigarh,Chandigarh,India,2025-08-13,HIGH,0
2003,102995,Chandran Sagar,chandran.sagar678@yahoo.com,4259900284,Male,1968-06-27,Lucknow,Uttar Pradesh,India,2023-11-17,LOW,0
2004,102997,WARJAS Garde,warjas.garde374@hotmail.com,3581368220,Male,1964-07-14,Nagpur,Maharashtra,India,2024-05-01,HIGH,1
2005,102998,Oliver Dugal,oliver.dugal673@yahoo.com,5462116700,Male,1980-08-18,Indore,Madhya Pradesh,India,2024-08-11,HIGH,0

## **--------------Storing customer_info Tables Datas In sql-server--------------------**

In [26]:
import urllib
import logging
from sqlalchemy import create_engine


# ---------------------------------------------------------
# Logging Configuration
# ---------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    filename = 'D:\project_pandas\project_01\log\load_cleaned_data_in_sql-server.logs',
    format="%(asctime)s | %(levelname)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    force = True
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------
# SQL Server Configuration
# ---------------------------------------------------------

SERVER = r"MADARA7998\SQLEXPRESS"
DATABASE = "ecommerce_db"
TABLE_NAME = "customer_info"
SCHEMA = "godl"


# ---------------------------------------------------------
# Create SQL Server Connection
# ---------------------------------------------------------

logger.info("Creating SQL Server connection...")

connection_string = (
    "DRIVER={ODBC Driver 17 for SQL Server};"
    f"SERVER={SERVER};"
    f"DATABASE={DATABASE};"
    "Trusted_Connection=yes;"
)

params = urllib.parse.quote_plus(connection_string)

engine = create_engine(
    f"mssql+pyodbc:///?odbc_connect={params}"
)

logger.info("SQLAlchemy engine created successfully.")


# ---------------------------------------------------------
# Upload DataFrame to SQL Server
# ---------------------------------------------------------

try:
    logger.info(
        "Starting data upload: %s.%s",
        SCHEMA,
        TABLE_NAME
    )

    logger.info(
        "Rows to upload: %s",
        len(customer_data)
    )

    customer_data.to_sql(
        name=TABLE_NAME,
        schema=SCHEMA,
        con=engine,
        if_exists="replace",
        index=False,
        chunksize=500
    )

    logger.info(
        "Data uploaded successfully to [%s].[%s]",
        SCHEMA,
        TABLE_NAME
    )
    print(f"Data uploaded successfully to scheme : {SCHEMA}  & table : {TABLE_NAME}" )

except Exception as e:
    logger.exception(
        "Error uploading data to SQL Server: %s",
        e
    )
    print("Error uploading data to SQL Server: %s",e)

Data uploaded successfully to scheme : godl  & table : customer_info